In [2]:
import numpy as np

In [4]:
a = np.arange(10,110, 10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [9]:
a = np.array([chr(i) for i in range(ord('a'), ord('z') + 1)])
print(a)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


In [11]:
df = np.zeros(10)
df.dtype

dtype('float64')

In [15]:
print(np.ones((2,3,4)))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [16]:
print(np.random.randint(1,6,10))

[5 3 4 4 5 5 4 5 3 4]


In [17]:
print(np.random.normal(5,1,10))

[4.23432095 5.82615971 4.91866277 5.63061022 6.29616865 4.71162381
 6.47584375 5.86667071 4.72924087 3.93810699]


In [21]:
print(np.random.rand(10))

[0.39779078 0.93776728 0.7940758  0.20604352 0.66744892 0.98568921
 0.20457416 0.34141041 0.51884498 0.4691593 ]


In [ ]:
print(np.random.uniform(1, 5, size=10))

[2.50717189 1.77506597 1.91556455 2.23083796 4.77412484 1.88882532
 2.12077916 3.80660132 2.55954553 4.45839908]


In [27]:
arr1 = np.arange(1,13, 1)
reshaped = arr1.reshape(3,4)
print(arr1)
print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
a = np.random.rand(10)
new_a = a.copy()
print(new_a)
print(a)

[0.66965691 0.06578035 0.92374844 0.63603305 0.84473911 0.66961713
 0.02420945 0.38817749 0.15687178 0.84527106]
[0.66965691 0.06578035 0.92374844 0.63603305 0.84473911 0.66961713
 0.02420945 0.38817749 0.15687178 0.84527106]


In [39]:
values = np.random.randint(1, 11, (3,4))
print(values)

[[10 10  9 10]
 [ 8  7  1  6]
 [ 9 10  1 10]]


In [40]:
z_list = [z for z in range(0,5)]
y_list = [z_list for y in range(0,4)]
x_list = [y_list for x in range(0,3)]

x_array = np.array(x_list)
print(x_array)

[[[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]


In [44]:
arr = np.array([[0, 1, 2],
       [3, 4, 5]])

print(arr.transpose())

[[0 3]
 [1 4]
 [2 5]]


In [46]:
four_by_five = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [47]:
print(four_by_five[:,0])

[ 1  6 11 16]


In [48]:
print(four_by_five[:, 3:])


[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]


In [49]:
print(four_by_five[1:3, 3:])


[[ 9 10]
 [14 15]]


In [50]:
one_dim = np.arange(1,6)
one_dim


array([1, 2, 3, 4, 5])

In [51]:
print(one_dim*2)

[ 2  4  6  8 10]


In [52]:
one_dim + np.arange(5, 0, -1)

array([6, 6, 6, 6, 6])

In [53]:
one_dim > 2

array([False, False,  True,  True,  True])

In [55]:
np.absolute(-(one_dim[3:]))

array([4, 5])

In [56]:
one_dim.sum()

np.int64(15)

In [3]:
arr5 = np.array([[11,12,13,14], [15,16,17,18]])
print(arr5[::,1])

[12 16]


In [8]:
arr6 = np.array([1,2,3,4], dtype = 'S')
print(arr6)

[b'1' b'2' b'3' b'4']


In [12]:
arr6 = arr6.astype(float)
print(arr6)

[1. 2. 3. 4.]


In [13]:
arr7 = arr6.copy()

In [14]:
arr8 = arr6.view()
arr8[0] = 123
print(arr6[0])

123.0


In [16]:
print(arr8.base)
print(arr7.base)

[123.   2.   3.   4.]
None


In [17]:
arr9 = np.vstack((arr6, arr7))
print(arr9)

[[123.   2.   3.   4.]
 [  1.   2.   3.   4.]]


In [25]:
arr10 = (arr9 >= 2) & (arr9 < 3)
print(arr10)

values, counts = np.unique(arr10, return_counts=True)
print(dict(zip(values, counts)))

np.count_nonzero(arr10)
print(arr10.sum())

[[False  True False False]
 [False  True False False]]
{np.False_: np.int64(6), np.True_: np.int64(2)}
2
